# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vad_pb2 as vad__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vad_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VADServiceStub(object):
    """VAD service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessAudio = channel.stream_stream(
                '/vad.VADService/ProcessAudio',
                request_serializer=vad__pb2.AudioChunk.SerializeToString,
                response_deserializer=vad__pb2.VADResponse.FromString,
                _registered_method=True)
        self.ResetVAD = channel.unary_unary(
                '/vad.VADService/ResetVAD',
                request_serializer=vad__pb2.ResetRequest.SerializeToString,
                response_deserializer=vad__pb2.ResetResponse.FromString,
                _registered_method=True)


class VADServiceServicer(object):
    """VAD service definition
    """

    def ProcessAudio(self, request_iterator, context):
        """Process streaming audio and get VAD events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetVAD(self, request, context):
        """Reset VAD state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VADServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessAudio,
                    request_deserializer=vad__pb2.AudioChunk.FromString,
                    response_serializer=vad__pb2.VADResponse.SerializeToString,
            ),
            'ResetVAD': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetVAD,
                    request_deserializer=vad__pb2.ResetRequest.FromString,
                    response_serializer=vad__pb2.ResetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vad.VADService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vad.VADService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VADService(object):
    """VAD service definition
    """

    @staticmethod
    def ProcessAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vad.VADService/ProcessAudio',
            vad__pb2.AudioChunk.SerializeToString,
            vad__pb2.VADResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetVAD(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vad.VADService/ResetVAD',
            vad__pb2.ResetRequest.SerializeToString,
            vad__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
