# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vad.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'vad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvad.proto\x12\x03vad\" \n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"-\n\x0bVADResponse\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0e\n\x0cResetRequest\" \n\rResetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32v\n\nVADService\x12\x35\n\x0cProcessAudio\x12\x0f.vad.AudioChunk\x1a\x10.vad.VADResponse(\x01\x30\x01\x12\x31\n\x08ResetVAD\x12\x11.vad.ResetRequest\x1a\x12.vad.ResetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=18
  _globals['_AUDIOCHUNK']._serialized_end=50
  _globals['_VADRESPONSE']._serialized_start=52
  _globals['_VADRESPONSE']._serialized_end=97
  _globals['_RESETREQUEST']._serialized_start=99
  _globals['_RESETREQUEST']._serialized_end=113
  _globals['_RESETRESPONSE']._serialized_start=115
  _globals['_RESETRESPONSE']._serialized_end=147
  _globals['_VADSERVICE']._serialized_start=149
  _globals['_VADSERVICE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
